/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/classlist': RouteRecordInfo<'/admin/classlist', '/admin/classlist', Record<never, never>, Record<never, never>>,
    '/admin/userlist': RouteRecordInfo<'/admin/userlist', '/admin/userlist', Record<never, never>, Record<never, never>>,
    '/classes': RouteRecordInfo<'/classes', '/classes', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/settings': RouteRecordInfo<'/dashboard/settings', '/dashboard/settings', Record<never, never>, Record<never, never>>,
    '/dashboard/useredit': RouteRecordInfo<'/dashboard/useredit', '/dashboard/useredit', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/more/careers': RouteRecordInfo<'/more/careers', '/more/careers', Record<never, never>, Record<never, never>>,
    '/more/contactus': RouteRecordInfo<'/more/contactus', '/more/contactus', Record<never, never>, Record<never, never>>,
    '/more/Memberships': RouteRecordInfo<'/more/Memberships', '/more/Memberships', Record<never, never>, Record<never, never>>,
    '/posting': RouteRecordInfo<'/posting', '/posting', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/statistics': RouteRecordInfo<'/statistics', '/statistics', Record<never, never>, Record<never, never>>,
  }
}
