/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activity': RouteRecordInfo<'/activity', '/activity', Record<never, never>, Record<never, never>>,
    '/Admin/': RouteRecordInfo<'/Admin/', '/Admin', Record<never, never>, Record<never, never>>,
    '/ErrorPage': RouteRecordInfo<'/ErrorPage', '/ErrorPage', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/More/About': RouteRecordInfo<'/More/About', '/More/About', Record<never, never>, Record<never, never>>,
    '/More/careers': RouteRecordInfo<'/More/careers', '/More/careers', Record<never, never>, Record<never, never>>,
    '/More/contact': RouteRecordInfo<'/More/contact', '/More/contact', Record<never, never>, Record<never, never>>,
    '/More/Member': RouteRecordInfo<'/More/Member', '/More/Member', Record<never, never>, Record<never, never>>,
    '/More/Testimonial': RouteRecordInfo<'/More/Testimonial', '/More/Testimonial', Record<never, never>, Record<never, never>>,
    '/posting': RouteRecordInfo<'/posting', '/posting', Record<never, never>, Record<never, never>>,
    '/Products/': RouteRecordInfo<'/Products/', '/Products', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/SignUp': RouteRecordInfo<'/SignUp', '/SignUp', Record<never, never>, Record<never, never>>,
    '/statistics': RouteRecordInfo<'/statistics', '/statistics', Record<never, never>, Record<never, never>>,
  }
}
